"""create analysis runs table

Revision ID: 1c87cd839fee
Revises: 0c77b58db562
Create Date: 2026-08-11 12:59:44.132182

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c87cd839fee'
down_revision: Union[str, Sequence[str], None] = '0c77b58db562'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis_runs',
    sa.Column('analysis_run_id', sa.String(length=50), nullable=False),
    sa.Column('feedback_id', sa.String(length=50), nullable=False),
    sa.Column('workspace_id', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['feedback_id'], ['feedback.feedback_id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.workspace_id'], ),
    sa.PrimaryKeyConstraint('analysis_run_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('analysis_runs')
    # ### end Alembic commands ###
