"""create extracted rules table

Revision ID: 2177bd71d4d9
Revises: 1fdd74e6d826
Create Date: 2026-08-11 13:18:24.300449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2177bd71d4d9'
down_revision: Union[str, Sequence[str], None] = '1fdd74e6d826'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('extracted_rules',
    sa.Column('extracted_rule_id', sa.String(length=50), nullable=False),
    sa.Column('workspace_id', sa.String(length=50), nullable=False),
    sa.Column('feedback_id', sa.String(length=50), nullable=False),
    sa.Column('analysis_run_id', sa.String(length=50), nullable=False),
    sa.Column('rule_data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_run_id'], ['analysis_runs.analysis_run_id'], ),
    sa.ForeignKeyConstraint(['feedback_id'], ['feedback.feedback_id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.workspace_id'], ),
    sa.PrimaryKeyConstraint('extracted_rule_id')
    )
    op.create_table('rule_suggestions',
    sa.Column('suggestion_id', sa.String(length=50), nullable=False),
    sa.Column('workspace_id', sa.String(length=50), nullable=False),
    sa.Column('feedback_id', sa.String(length=50), nullable=False),
    sa.Column('analysis_run_id', sa.String(length=50), nullable=False),
    sa.Column('suggested_rule', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_run_id'], ['analysis_runs.analysis_run_id'], ),
    sa.ForeignKeyConstraint(['feedback_id'], ['feedback.feedback_id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.workspace_id'], ),
    sa.PrimaryKeyConstraint('suggestion_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rule_suggestions')
    op.drop_table('extracted_rules')
    # ### end Alembic commands ###
