"""add background job idempotency constraint

Revision ID: 2a52c1d14894
Revises: d626a8c1752b
Create Date: 2026-08-21 11:48:50.876466

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a52c1d14894'
down_revision: Union[str, Sequence[str], None] = 'd626a8c1752b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_background_jobs_workspace_idempotency', 'background_jobs', ['workspace_id', 'idempotency_key'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_background_jobs_workspace_idempotency', 'background_jobs', type_='unique')
    # ### end Alembic commands ###
