"""create clarifications table

Revision ID: 5d2d4618cec2
Revises: 2177bd71d4d9
Create Date: 2026-08-11 13:19:48.903057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d2d4618cec2'
down_revision: Union[str, Sequence[str], None] = '2177bd71d4d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clarifications',
    sa.Column('clarification_id', sa.String(length=50), nullable=False),
    sa.Column('workspace_id', sa.String(length=50), nullable=False),
    sa.Column('feedback_id', sa.String(length=50), nullable=False),
    sa.Column('analysis_run_id', sa.String(length=50), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_run_id'], ['analysis_runs.analysis_run_id'], ),
    sa.ForeignKeyConstraint(['feedback_id'], ['feedback.feedback_id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.workspace_id'], ),
    sa.PrimaryKeyConstraint('clarification_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('clarifications')
    # ### end Alembic commands ###
