"""add model version uniqueness constraint

Revision ID: 70f8421d8630
Revises: 2a52c1d14894
Create Date: 2026-08-21 13:00:00.233262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70f8421d8630'
down_revision: Union[str, Sequence[str], None] = '2a52c1d14894'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_model_versions_name_version', 'model_versions', ['model_name', 'version'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_model_versions_name_version', 'model_versions', type_='unique')
    # ### end Alembic commands ###
