"""create rules table

Revision ID: c63426f2271b
Revises: f99cd605967b
Create Date: 2026-08-11 12:51:51.932266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c63426f2271b'
down_revision: Union[str, Sequence[str], None] = 'f99cd605967b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rules',
    sa.Column('rule_id', sa.String(length=50), nullable=False),
    sa.Column('workspace_id', sa.String(length=50), nullable=False),
    sa.Column('rule_category', sa.String(length=100), nullable=False),
    sa.Column('operation', sa.String(length=50), nullable=False),
    sa.Column('conditions', sa.JSON(), nullable=False),
    sa.Column('affected_tables', sa.JSON(), nullable=False),
    sa.Column('affected_columns', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.workspace_id'], ),
    sa.PrimaryKeyConstraint('rule_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rules')
    # ### end Alembic commands ###
